import { z } from "zod/v4";
import * as types from "./types";
import * as primitives from "../primitives";
import { getCachedSchema } from "../schema-cache";
import {
  createExtensionSchema,
  createElementSchema,
  createCodingSchema,
  createAddressSchema,
  createAgeSchema,
  createAnnotationSchema,
  createAttachmentSchema,
  createCodeableConceptSchema,
  createContactPointSchema,
  createCountSchema,
  createDistanceSchema,
  createDurationSchema,
  createHumanNameSchema,
  createIdentifierSchema,
  createMoneySchema,
  createPeriodSchema,
  createQuantitySchema,
  createRangeSchema,
  createRatioSchema,
  createReferenceSchema,
  createSampledDataSchema,
  createSignatureSchema,
  createTimingSchema,
  createContactDetailSchema,
  createContributorSchema,
  createDataRequirementSchema,
  createExpressionSchema,
  createParameterDefinitionSchema,
  createRelatedArtifactSchema,
  createTriggerDefinitionSchema,
  createUsageContextSchema,
  createDosageSchema,
  createMetaSchema,
} from "../core/schema";
import { createElementDefinitionSlicingSchema } from "../elementdefinitionslicing/schema";
import { createElementDefinitionBaseSchema } from "../elementdefinitionbase/schema";
import { createElementDefinitionTypeSchema } from "../elementdefinitiontype/schema";
import { createElementDefinitionExampleSchema } from "../elementdefinitionexample/schema";
import { createElementDefinitionConstraintSchema } from "../elementdefinitionconstraint/schema";
import { createElementDefinitionBindingSchema } from "../elementdefinitionbinding/schema";
import { createElementDefinitionMappingSchema } from "../elementdefinitionmapping/schema";

/* Generated from FHIR JSON Schema */

export function createElementDefinitionSchema() {
  return getCachedSchema("ElementDefinition", () => {
    const baseSchema: z.ZodType<types.ElementDefinition> = z.strictObject({
      id: primitives.getStringSchema().optional(),
      extension: z.array(createExtensionSchema()).optional(),
      modifierExtension: z.array(createExtensionSchema()).optional(),
      path: primitives.getStringSchema(),
      _path: createElementSchema().optional(),
      representation: z
        .enum(["xmlAttr", "xmlText", "typeAttr", "cdaText", "xhtml"])
        .array()
        .optional(),
      _representation: z.array(createElementSchema()).optional(),
      sliceName: primitives.getStringSchema().optional(),
      _sliceName: createElementSchema().optional(),
      sliceIsConstraining: primitives.getBooleanSchema().optional(),
      _sliceIsConstraining: createElementSchema().optional(),
      label: primitives.getStringSchema().optional(),
      _label: createElementSchema().optional(),
      code: z.array(createCodingSchema()).optional(),
      slicing: createElementDefinitionSlicingSchema().optional(),
      short: primitives.getStringSchema().optional(),
      _short: createElementSchema().optional(),
      definition: primitives.getMarkdownSchema().optional(),
      _definition: createElementSchema().optional(),
      comment: primitives.getMarkdownSchema().optional(),
      _comment: createElementSchema().optional(),
      requirements: primitives.getMarkdownSchema().optional(),
      _requirements: createElementSchema().optional(),
      alias: z.array(primitives.getStringSchema()).optional(),
      _alias: z.array(createElementSchema()).optional(),
      min: primitives.getUnsignedIntSchema().optional(),
      _min: createElementSchema().optional(),
      max: primitives.getStringSchema().optional(),
      _max: createElementSchema().optional(),
      base: createElementDefinitionBaseSchema().optional(),
      contentReference: primitives.getUriSchema().optional(),
      _contentReference: createElementSchema().optional(),
      type: z.array(createElementDefinitionTypeSchema()).optional(),
      defaultValueBase64Binary: z.string().optional(),
      _defaultValueBase64Binary: createElementSchema().optional(),
      defaultValueBoolean: z.boolean().optional(),
      _defaultValueBoolean: createElementSchema().optional(),
      defaultValueCanonical: z.string().optional(),
      _defaultValueCanonical: createElementSchema().optional(),
      defaultValueCode: z.string().optional(),
      _defaultValueCode: createElementSchema().optional(),
      defaultValueDate: z.string().optional(),
      _defaultValueDate: createElementSchema().optional(),
      defaultValueDateTime: z.string().optional(),
      _defaultValueDateTime: createElementSchema().optional(),
      defaultValueDecimal: z.number().optional(),
      _defaultValueDecimal: createElementSchema().optional(),
      defaultValueId: z.string().optional(),
      _defaultValueId: createElementSchema().optional(),
      defaultValueInstant: z.string().optional(),
      _defaultValueInstant: createElementSchema().optional(),
      defaultValueInteger: z.number().optional(),
      _defaultValueInteger: createElementSchema().optional(),
      defaultValueMarkdown: z.string().optional(),
      _defaultValueMarkdown: createElementSchema().optional(),
      defaultValueOid: z.string().optional(),
      _defaultValueOid: createElementSchema().optional(),
      defaultValuePositiveInt: z.number().optional(),
      _defaultValuePositiveInt: createElementSchema().optional(),
      defaultValueString: z.string().optional(),
      _defaultValueString: createElementSchema().optional(),
      defaultValueTime: z.string().optional(),
      _defaultValueTime: createElementSchema().optional(),
      defaultValueUnsignedInt: z.number().optional(),
      _defaultValueUnsignedInt: createElementSchema().optional(),
      defaultValueUri: z.string().optional(),
      _defaultValueUri: createElementSchema().optional(),
      defaultValueUrl: z.string().optional(),
      _defaultValueUrl: createElementSchema().optional(),
      defaultValueUuid: z.string().optional(),
      _defaultValueUuid: createElementSchema().optional(),
      defaultValueAddress: createAddressSchema().optional(),
      defaultValueAge: createAgeSchema().optional(),
      defaultValueAnnotation: createAnnotationSchema().optional(),
      defaultValueAttachment: createAttachmentSchema().optional(),
      defaultValueCodeableConcept: createCodeableConceptSchema().optional(),
      defaultValueCoding: createCodingSchema().optional(),
      defaultValueContactPoint: createContactPointSchema().optional(),
      defaultValueCount: createCountSchema().optional(),
      defaultValueDistance: createDistanceSchema().optional(),
      defaultValueDuration: createDurationSchema().optional(),
      defaultValueHumanName: createHumanNameSchema().optional(),
      defaultValueIdentifier: createIdentifierSchema().optional(),
      defaultValueMoney: createMoneySchema().optional(),
      defaultValuePeriod: createPeriodSchema().optional(),
      defaultValueQuantity: createQuantitySchema().optional(),
      defaultValueRange: createRangeSchema().optional(),
      defaultValueRatio: createRatioSchema().optional(),
      defaultValueReference: createReferenceSchema().optional(),
      defaultValueSampledData: createSampledDataSchema().optional(),
      defaultValueSignature: createSignatureSchema().optional(),
      defaultValueTiming: createTimingSchema().optional(),
      defaultValueContactDetail: createContactDetailSchema().optional(),
      defaultValueContributor: createContributorSchema().optional(),
      defaultValueDataRequirement: createDataRequirementSchema().optional(),
      defaultValueExpression: createExpressionSchema().optional(),
      defaultValueParameterDefinition:
        createParameterDefinitionSchema().optional(),
      defaultValueRelatedArtifact: createRelatedArtifactSchema().optional(),
      defaultValueTriggerDefinition: createTriggerDefinitionSchema().optional(),
      defaultValueUsageContext: createUsageContextSchema().optional(),
      defaultValueDosage: createDosageSchema().optional(),
      defaultValueMeta: createMetaSchema().optional(),
      meaningWhenMissing: primitives.getMarkdownSchema().optional(),
      _meaningWhenMissing: createElementSchema().optional(),
      orderMeaning: primitives.getStringSchema().optional(),
      _orderMeaning: createElementSchema().optional(),
      fixedBase64Binary: z.string().optional(),
      _fixedBase64Binary: createElementSchema().optional(),
      fixedBoolean: z.boolean().optional(),
      _fixedBoolean: createElementSchema().optional(),
      fixedCanonical: z.string().optional(),
      _fixedCanonical: createElementSchema().optional(),
      fixedCode: z.string().optional(),
      _fixedCode: createElementSchema().optional(),
      fixedDate: z.string().optional(),
      _fixedDate: createElementSchema().optional(),
      fixedDateTime: z.string().optional(),
      _fixedDateTime: createElementSchema().optional(),
      fixedDecimal: z.number().optional(),
      _fixedDecimal: createElementSchema().optional(),
      fixedId: z.string().optional(),
      _fixedId: createElementSchema().optional(),
      fixedInstant: z.string().optional(),
      _fixedInstant: createElementSchema().optional(),
      fixedInteger: z.number().optional(),
      _fixedInteger: createElementSchema().optional(),
      fixedMarkdown: z.string().optional(),
      _fixedMarkdown: createElementSchema().optional(),
      fixedOid: z.string().optional(),
      _fixedOid: createElementSchema().optional(),
      fixedPositiveInt: z.number().optional(),
      _fixedPositiveInt: createElementSchema().optional(),
      fixedString: z.string().optional(),
      _fixedString: createElementSchema().optional(),
      fixedTime: z.string().optional(),
      _fixedTime: createElementSchema().optional(),
      fixedUnsignedInt: z.number().optional(),
      _fixedUnsignedInt: createElementSchema().optional(),
      fixedUri: z.string().optional(),
      _fixedUri: createElementSchema().optional(),
      fixedUrl: z.string().optional(),
      _fixedUrl: createElementSchema().optional(),
      fixedUuid: z.string().optional(),
      _fixedUuid: createElementSchema().optional(),
      fixedAddress: createAddressSchema().optional(),
      fixedAge: createAgeSchema().optional(),
      fixedAnnotation: createAnnotationSchema().optional(),
      fixedAttachment: createAttachmentSchema().optional(),
      fixedCodeableConcept: createCodeableConceptSchema().optional(),
      fixedCoding: createCodingSchema().optional(),
      fixedContactPoint: createContactPointSchema().optional(),
      fixedCount: createCountSchema().optional(),
      fixedDistance: createDistanceSchema().optional(),
      fixedDuration: createDurationSchema().optional(),
      fixedHumanName: createHumanNameSchema().optional(),
      fixedIdentifier: createIdentifierSchema().optional(),
      fixedMoney: createMoneySchema().optional(),
      fixedPeriod: createPeriodSchema().optional(),
      fixedQuantity: createQuantitySchema().optional(),
      fixedRange: createRangeSchema().optional(),
      fixedRatio: createRatioSchema().optional(),
      fixedReference: createReferenceSchema().optional(),
      fixedSampledData: createSampledDataSchema().optional(),
      fixedSignature: createSignatureSchema().optional(),
      fixedTiming: createTimingSchema().optional(),
      fixedContactDetail: createContactDetailSchema().optional(),
      fixedContributor: createContributorSchema().optional(),
      fixedDataRequirement: createDataRequirementSchema().optional(),
      fixedExpression: createExpressionSchema().optional(),
      fixedParameterDefinition: createParameterDefinitionSchema().optional(),
      fixedRelatedArtifact: createRelatedArtifactSchema().optional(),
      fixedTriggerDefinition: createTriggerDefinitionSchema().optional(),
      fixedUsageContext: createUsageContextSchema().optional(),
      fixedDosage: createDosageSchema().optional(),
      fixedMeta: createMetaSchema().optional(),
      patternBase64Binary: z.string().optional(),
      _patternBase64Binary: createElementSchema().optional(),
      patternBoolean: z.boolean().optional(),
      _patternBoolean: createElementSchema().optional(),
      patternCanonical: z.string().optional(),
      _patternCanonical: createElementSchema().optional(),
      patternCode: z.string().optional(),
      _patternCode: createElementSchema().optional(),
      patternDate: z.string().optional(),
      _patternDate: createElementSchema().optional(),
      patternDateTime: z.string().optional(),
      _patternDateTime: createElementSchema().optional(),
      patternDecimal: z.number().optional(),
      _patternDecimal: createElementSchema().optional(),
      patternId: z.string().optional(),
      _patternId: createElementSchema().optional(),
      patternInstant: z.string().optional(),
      _patternInstant: createElementSchema().optional(),
      patternInteger: z.number().optional(),
      _patternInteger: createElementSchema().optional(),
      patternMarkdown: z.string().optional(),
      _patternMarkdown: createElementSchema().optional(),
      patternOid: z.string().optional(),
      _patternOid: createElementSchema().optional(),
      patternPositiveInt: z.number().optional(),
      _patternPositiveInt: createElementSchema().optional(),
      patternString: z.string().optional(),
      _patternString: createElementSchema().optional(),
      patternTime: z.string().optional(),
      _patternTime: createElementSchema().optional(),
      patternUnsignedInt: z.number().optional(),
      _patternUnsignedInt: createElementSchema().optional(),
      patternUri: z.string().optional(),
      _patternUri: createElementSchema().optional(),
      patternUrl: z.string().optional(),
      _patternUrl: createElementSchema().optional(),
      patternUuid: z.string().optional(),
      _patternUuid: createElementSchema().optional(),
      patternAddress: createAddressSchema().optional(),
      patternAge: createAgeSchema().optional(),
      patternAnnotation: createAnnotationSchema().optional(),
      patternAttachment: createAttachmentSchema().optional(),
      patternCodeableConcept: createCodeableConceptSchema().optional(),
      patternCoding: createCodingSchema().optional(),
      patternContactPoint: createContactPointSchema().optional(),
      patternCount: createCountSchema().optional(),
      patternDistance: createDistanceSchema().optional(),
      patternDuration: createDurationSchema().optional(),
      patternHumanName: createHumanNameSchema().optional(),
      patternIdentifier: createIdentifierSchema().optional(),
      patternMoney: createMoneySchema().optional(),
      patternPeriod: createPeriodSchema().optional(),
      patternQuantity: createQuantitySchema().optional(),
      patternRange: createRangeSchema().optional(),
      patternRatio: createRatioSchema().optional(),
      patternReference: createReferenceSchema().optional(),
      patternSampledData: createSampledDataSchema().optional(),
      patternSignature: createSignatureSchema().optional(),
      patternTiming: createTimingSchema().optional(),
      patternContactDetail: createContactDetailSchema().optional(),
      patternContributor: createContributorSchema().optional(),
      patternDataRequirement: createDataRequirementSchema().optional(),
      patternExpression: createExpressionSchema().optional(),
      patternParameterDefinition: createParameterDefinitionSchema().optional(),
      patternRelatedArtifact: createRelatedArtifactSchema().optional(),
      patternTriggerDefinition: createTriggerDefinitionSchema().optional(),
      patternUsageContext: createUsageContextSchema().optional(),
      patternDosage: createDosageSchema().optional(),
      patternMeta: createMetaSchema().optional(),
      example: z.array(createElementDefinitionExampleSchema()).optional(),
      minValueDate: z.string().optional(),
      _minValueDate: createElementSchema().optional(),
      minValueDateTime: z.string().optional(),
      _minValueDateTime: createElementSchema().optional(),
      minValueInstant: z.string().optional(),
      _minValueInstant: createElementSchema().optional(),
      minValueTime: z.string().optional(),
      _minValueTime: createElementSchema().optional(),
      minValueDecimal: z.number().optional(),
      _minValueDecimal: createElementSchema().optional(),
      minValueInteger: z.number().optional(),
      _minValueInteger: createElementSchema().optional(),
      minValuePositiveInt: z.number().optional(),
      _minValuePositiveInt: createElementSchema().optional(),
      minValueUnsignedInt: z.number().optional(),
      _minValueUnsignedInt: createElementSchema().optional(),
      minValueQuantity: createQuantitySchema().optional(),
      maxValueDate: z.string().optional(),
      _maxValueDate: createElementSchema().optional(),
      maxValueDateTime: z.string().optional(),
      _maxValueDateTime: createElementSchema().optional(),
      maxValueInstant: z.string().optional(),
      _maxValueInstant: createElementSchema().optional(),
      maxValueTime: z.string().optional(),
      _maxValueTime: createElementSchema().optional(),
      maxValueDecimal: z.number().optional(),
      _maxValueDecimal: createElementSchema().optional(),
      maxValueInteger: z.number().optional(),
      _maxValueInteger: createElementSchema().optional(),
      maxValuePositiveInt: z.number().optional(),
      _maxValuePositiveInt: createElementSchema().optional(),
      maxValueUnsignedInt: z.number().optional(),
      _maxValueUnsignedInt: createElementSchema().optional(),
      maxValueQuantity: createQuantitySchema().optional(),
      maxLength: primitives.getIntegerSchema().optional(),
      _maxLength: createElementSchema().optional(),
      condition: z.array(primitives.getIdSchema()).optional(),
      _condition: z.array(createElementSchema()).optional(),
      constraint: z.array(createElementDefinitionConstraintSchema()).optional(),
      mustSupport: primitives.getBooleanSchema().optional(),
      _mustSupport: createElementSchema().optional(),
      isModifier: primitives.getBooleanSchema().optional(),
      _isModifier: createElementSchema().optional(),
      isModifierReason: primitives.getStringSchema().optional(),
      _isModifierReason: createElementSchema().optional(),
      isSummary: primitives.getBooleanSchema().optional(),
      _isSummary: createElementSchema().optional(),
      binding: createElementDefinitionBindingSchema().optional(),
      mapping: z.array(createElementDefinitionMappingSchema()).optional(),
    });

    return baseSchema;
  });
}
