name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - packages/fhir-r4
          - packages/fhir-r4-server
        node-version:
          - '20.x'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: npm install
      - name: Run CI
        working-directory: ${{ matrix.package }}
        run: npm run ci
